### ISSUE TITLE
RWX support ?

### ISSUE THREAD

**Issue by src386** [scaleway/scaleway-csi#24]
Trying to provision this PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: scw-bssd
  resources:
    requests:
      storage: 1Gi
```

Will return:
```
Warning  ProvisioningFailed    2s (x5 over 15s)   csi.scaleway.com_control-plane-6fc9f6bc79-6mrnj_7a3ef33f-c1b9-4e77-8d85-7fae980b5eca  failed to provision volume with StorageClass "scw-bssd": rpc error: code = InvalidArgument desc = volumeCapabilities not supported: access mode not supported
```

No RWX support means not usable in a Cluster.
