### ISSUE TITLE
Volume failed to mark as attached : Forbidden when patching volumeattachement/status

### ISSUE THREAD

**Issue by teknologista** [scaleway/scaleway-csi#39]
**Describe the bug**

We are seeing errors like this one after unsuccessful attach attempts.

We are trying to use the CSI driver to provision volumes in our kubernetes Cluster (Rancher RKE2).

In scaleway console everything looks good. Volumes are attached to the right instance (Kubernetes node running the deployment using the volume)

In Kubernetes, volumes appear as Bound but workload is stuck in creating state and shows error:

`AttachVolume.Attach failed for volume "pvc-c5602274-0c49-4167-b626-fd2d78ad8434" : attachdetachment timeout for volume fr-par-2/dc28587c-fe28-403f-854e-2d3f05ce76be`

Digging into the cis-attacher pod we see these errors:

`I0920 11:30:20.498831       1 csi_handler.go:226] Error processing "csi-37c384c5d58e1937c2c7c055450fa082c5ec96a1295143dd0d61c5fbba077765": failed to mark as attached: volumeattachments.storage.k8s.io "csi-37c384c5d58e1937c2c7c055450fa082c5ec96a1295143dd0d61c5fbba077765" is forbidden: User "system:serviceaccount:kube-system:scaleway-csi-controller" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope
20/09/2021 13:30:20 I0920 11:30:20.500312       1 csi_handler.go:226] Error processing "csi-4adf5e26220b50a8219466691a8479f195cb34041094c4ad1dde34847fbbb2d8": failed to mark as attached: volumeattachments.storage.k8s.io "csi-4adf5e26220b50a8219466691a8479f195cb34041094c4ad1dde34847fbbb2d8" is forbidden: User "system:serviceaccount:kube-system:scaleway-csi-controller" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope
20/09/2021 13:30:21 
`

We have verified we did apply the cluster role and role bindings for the service account, yet we get this error.
Our cluster runs with a pod security policy but there doesn't seem to be any issue in that area...

**To Reproduce**
Install RKE2 cluster (RKE Govt)
add scaleway CSI driver
apply example pic and pod yaml from this repo

**Expected behavior**

**Details (please complete the following information):**
 - Scaleway CSI version: v0.1.5 and v0.1.7
 - Platform: Kubernetes v1.20.10+rke2r1 and Rancher 2.5.9
 - Orchestrator and its version:
Kubernetes v1.20.10+rke2r1 and Rancher 2.5.9
**Additional context**

We have successfully installed and use the Longhorn CSI in our cluster. We wanted to add the scaleway CSI to provision PVCs from "out of the cluster" in encrypted mode.

**Comment by teknologista** [comment]
Fixed by changing the scaleway-csi-attacher ClusterRole to this:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaleway-csi-attacher
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
```

See adding:

```
- apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
```

solved the issue.
This might be needed for Kubernetes 1.20+
