### ISSUE TITLE
Local SSD support

### ISSUE THREAD

**Issue by jgillich** [scaleway/scaleway-csi#43]
Can volumes with type `l_ssd` be supported? I tried adding a storage class for them:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: scw-lssd
provisioner: csi.scaleway.com
reclaimPolicy: Delete
parameters:
  type: l_ssd
```

But PVCs are just stuck on pending and there is no relevant log from the csi pod as far as I can tell.

Background for this is that I need object storage via Minio or Ceph and they strongly discourage network-attached storage. (I would prefer using Scaleway's object storage but the API key gives access to everything and that doesn't work for me)
